//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntermediatorBot.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConversationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConversationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntermediatorBot.Strings.ConversationText", typeof(ConversationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptButtonTitle {
            get {
                return ResourceManager.GetString("AcceptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the user whose request to accept.
        /// </summary>
        internal static string AcceptConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept request.
        /// </summary>
        internal static string AcceptConnectionRequestsCardTitle {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept or reject the request: Type &quot;{0}&quot; to accept, &quot;{1}&quot; to reject or use the buttons if enabled.
        /// </summary>
        internal static string AcceptRejectConnectionHint {
            get {
                return ResourceManager.GetString("AcceptRejectConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up an aggregation channel, type &quot;{0}&quot;.
        /// </summary>
        internal static string AddAggregationChannelCommandHint {
            get {
                return ResourceManager.GetString("AddAggregationChannelCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel/conversation is already receiving requests.
        /// </summary>
        internal static string AggregationChannelAlreadySet {
            get {
                return ResourceManager.GetString("AggregationChannelAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel/conversation will no longer receive requests.
        /// </summary>
        internal static string AggregationChannelRemoved {
            get {
                return ResourceManager.GetString("AggregationChannelRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This channel/conversation is now where the requests are aggregated.
        /// </summary>
        internal static string AggregationChannelSet {
            get {
                return ResourceManager.GetString("AggregationChannelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already connected with user &quot;{0}&quot;.
        /// </summary>
        internal static string AlreadyConnectedWithUser {
            get {
                return ResourceManager.GetString("AlreadyConnectedWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all.
        /// </summary>
        internal static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        internal static string Bots {
            get {
                return ResourceManager.GetString("Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative options for controlling the end user bot conversations.
        /// </summary>
        internal static string CommandMenuDescription {
            get {
                return ResourceManager.GetString("CommandMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the command using the buttons below or type the command keyword (&quot;{0}&quot;)/bot handle (&quot;@{1}&quot;) followed by the command and its parameters (if any), for example: &quot;{2}&quot;..
        /// </summary>
        internal static string CommandMenuInstructions {
            get {
                return ResourceManager.GetString("CommandMenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string CommandMenuTitle {
            get {
                return ResourceManager.GetString("CommandMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; not recognized.
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection request was made, but the requestor party is null.
        /// </summary>
        internal static string ConnectionRequestMadeButRequestorIsNull {
            get {
                return ResourceManager.GetString("ConnectionRequestMadeButRequestorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not allowed to accept or reject requests.
        /// </summary>
        internal static string ConnectionRequestResponseNotAllowed {
            get {
                return ResourceManager.GetString("ConnectionRequestResponseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance request.
        /// </summary>
        internal static string ConnectionRequestTitle {
            get {
                return ResourceManager.GetString("ConnectionRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To initiate a conversation with an agent, type &quot;{0}&quot;.
        /// </summary>
        internal static string ConnectRequestCommandHint {
            get {
                return ResourceManager.GetString("ConnectRequestCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all data....
        /// </summary>
        internal static string DeletingAllData {
            get {
                return ResourceManager.GetString("DeletingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all data as requested by &quot;0&quot;....
        /// </summary>
        internal static string DeletingAllDataWithCommandIssuer {
            get {
                return ResourceManager.GetString("DeletingAllDataWithCommandIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said: {0}.
        /// </summary>
        internal static string EchoMessage {
            get {
                return ResourceManager.GetString("EchoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured (result: {0}).
        /// </summary>
        internal static string ErrorOccuredWithResult {
            get {
                return ResourceManager.GetString("ErrorOccuredWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the bot party on aggregation channel &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToFindBotOnAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToFindBotOnAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the pending request.
        /// </summary>
        internal static string FailedToFindPendingRequest {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a pending request for user &quot;0&quot;: {1}.
        /// </summary>
        internal static string FailedToFindPendingRequestForUserWithErrorMessage {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequestForUserWithErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to forward the message.
        /// </summary>
        internal static string FailedToForwardMessage {
            get {
                return ResourceManager.GetString("FailedToForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reject pending requests.
        /// </summary>
        internal static string FailedToRejectPendingRequests {
            get {
                return ResourceManager.GetString("FailedToRejectPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove aggregation channel.
        /// </summary>
        internal static string FailedToRemoveAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToRemoveAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command parameter invalid or missing.
        /// </summary>
        internal static string InvalidOrMissingCommandParameter {
            get {
                return ResourceManager.GetString("InvalidOrMissingCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are no agents available right now.
        /// </summary>
        internal static string NoAgentsAvailable {
            get {
                return ResourceManager.GetString("NoAgentsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aggregation channel set up.
        /// </summary>
        internal static string NoAggregationChannel {
            get {
                return ResourceManager.GetString("NoAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bots stored.
        /// </summary>
        internal static string NoBotsStored {
            get {
                return ResourceManager.GetString("NoBotsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conversations.
        /// </summary>
        internal static string NoConversations {
            get {
                return ResourceManager.GetString("NoConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending requests.
        /// </summary>
        internal static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was accepted and you are now chatting with {0}.
        /// </summary>
        internal static string NotifyClientConnected {
            get {
                return ResourceManager.GetString("NotifyClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your conversation with {0} has ended.
        /// </summary>
        internal static string NotifyClientDisconnected {
            get {
                return ResourceManager.GetString("NotifyClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has already been received, please wait for an agent to respond.
        /// </summary>
        internal static string NotifyClientDuplicateRequest {
            get {
                return ResourceManager.GetString("NotifyClientDuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your request could not be processed.
        /// </summary>
        internal static string NotifyClientRequestRejected {
            get {
                return ResourceManager.GetString("NotifyClientRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for your request to be accepted.
        /// </summary>
        internal static string NotifyClientWaitForRequestHandling {
            get {
                return ResourceManager.GetString("NotifyClientWaitForRequestHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to user &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerConnected {
            get {
                return ResourceManager.GetString("NotifyOwnerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now disconnected from the conversation with user &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerDisconnected {
            get {
                return ResourceManager.GetString("NotifyOwnerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request from user &quot;{0}&quot; rejected.
        /// </summary>
        internal static string NotifyOwnerRequestRejected {
            get {
                return ResourceManager.GetString("NotifyOwnerRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users stored.
        /// </summary>
        internal static string NoUsersStored {
            get {
                return ResourceManager.GetString("NoUsersStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see the available commands, type &quot;{0}&quot;.
        /// </summary>
        internal static string OptionsCommandHint {
            get {
                return ResourceManager.GetString("OptionsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party &quot;{0}&quot; removed.
        /// </summary>
        internal static string PartyRemoved {
            get {
                return ResourceManager.GetString("PartyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pending request(s) found.
        /// </summary>
        internal static string PendingRequestsFoundWithCount {
            get {
                return ResourceManager.GetString("PendingRequestsFoundWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject all.
        /// </summary>
        internal static string RejectAll {
            get {
                return ResourceManager.GetString("RejectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject request.
        /// </summary>
        internal static string RejectConnectionRequestCardTitle {
            get {
                return ResourceManager.GetString("RejectConnectionRequestCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the user whose request to reject.
        /// </summary>
        internal static string RejectConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("RejectConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; on channel &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string RequestorDetailsItem {
            get {
                return ResourceManager.GetString("RequestorDetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was made, but the details of the requestor party are missing.
        /// </summary>
        internal static string RequestorDetailsMissing {
            get {
                return ResourceManager.GetString("RequestorDetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by user &quot;{0}&quot; on channel &quot;{1}&quot;.
        /// </summary>
        internal static string RequestorDetailsTitle {
            get {
                return ResourceManager.GetString("RequestorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of user &quot;{0}&quot; deleted.
        /// </summary>
        internal static string UserDataDeleted {
            get {
                return ResourceManager.GetString("UserDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name missing.
        /// </summary>
        internal static string UserNameMissing {
            get {
                return ResourceManager.GetString("UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
